services:
  - type: web
    name: planilla-obras
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: DATABASE_URL
        sync: false